# Generated by Django 5.1.3 on 2025-01-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_rentee',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_renter',
        ),
    ]
