# Generated by Django 5.1.3 on 2025-01-15 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_item', '0007_productimage_delete_itemimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
