# Generated by Django 5.1.3 on 2025-01-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_item', '0008_remove_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=200, upload_to='product_images/'),
        ),
    ]
