# Generated by Django 5.1.3 on 2025-01-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_item', '0009_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
